<?php

declare(strict_types=1);

namespace Cordon\Documentation;

use Cordon\Analysis\Edge;
use Cordon\Analysis\ModuleFilter;
use Cordon\Analysis\Snapshot;
use Cordon\Analysis\Violation;
use Cordon\Module\Module;
use Cordon\Rules\InternalAccessRule;
use Cordon\Support\Paths;

/**
 * Renders Markdown documentation of the real module architecture:
 * README.md (overview and global dependency diagram), modules/<Name>.md
 * (one canvas per module) and events.md (event inventory). Output is deterministic so it can be committed.
 */
final class DocumentationGenerator
{
    /**
     * @param  list<Violation>  $violations
     * @return array<string, string> file name => Markdown
     */
    public function generate(Snapshot $snapshot, array $violations, EventInventory $events, ?string $basePath = null): array
    {
        $modules = $snapshot->context->modules->all();
        $dependencies = $this->dependencies($snapshot->context->edges);
        $internal = $this->internalPairs($violations);

        $files = ['README.md' => $this->overview($modules, $dependencies, $internal, $violations, $events)];

        foreach ($modules as $module) {
            $files[$this->fileName($module)] = $this->canvas($module, $snapshot, $dependencies, $internal, $violations, $events, $basePath);
        }

        $files['events.md'] = $this->eventInventory($events, $basePath);

        return $files;
    }

    /**
     * @param  list<Module>  $modules
     * @param  array<string, array<string, array<string, true>>>  $dependencies  from => to => class => true
     * @param  array<string, true>  $internal  "from|to" pairs with internal access
     * @param  list<Violation>  $violations
     */
    private function overview(array $modules, array $dependencies, array $internal, array $violations, EventInventory $events): string
    {
        $lines = [
            '# Modules',
            '',
            '> Generated by `php artisan cordon:docs` from the code. Do not edit by hand.',
            '',
            sprintf('%d modules, %d events, %d boundary violations.', count($modules), count($events->events), count($violations)),
            '',
            '## Dependencies',
            '',
            ...$this->diagram(array_map(static fn (Module $module): string => $module->name, $modules), $dependencies, $internal),
            '',
            'Solid arrows are dependencies through the public API. Red arrows include internal access.',
            '',
            '| Module | Namespace | Depends on | Used by | Violations |',
            '|---|---|---|---|---|',
        ];

        foreach ($modules as $module) {
            $lines[] = sprintf(
                '| [%s](%s) | `%s` | %s | %s | %d |',
                $module->name,
                $this->fileName($module),
                $module->namespace,
                $this->list(array_keys($dependencies[$module->name] ?? [])),
                $this->list($this->usedBy($module->name, $dependencies)),
                count(array_filter($violations, static fn (Violation $v): bool => ModuleFilter::involves($v, $module->name))),
            );
        }

        $lines[] = '';
        $lines[] = 'See also the [event inventory](events.md).';

        return implode("\n", $lines)."\n";
    }

    /**
     * @param  array<string, array<string, array<string, true>>>  $dependencies
     * @param  array<string, true>  $internal
     * @param  list<Violation>  $violations
     */
    private function canvas(Module $module, Snapshot $snapshot, array $dependencies, array $internal, array $violations, EventInventory $events, ?string $basePath): string
    {
        $name = $module->name;
        $outgoing = $dependencies[$name] ?? [];
        $incoming = [];

        foreach ($dependencies as $from => $targets) {
            if (isset($targets[$name])) {
                $incoming[$from] = $targets[$name];
            }
        }

        ksort($incoming);
        $neighbours = array_values(array_unique([$name, ...array_keys($outgoing), ...array_keys($incoming)]));
        sort($neighbours);
        $local = [];

        foreach ($dependencies as $from => $targets) {
            foreach ($targets as $to => $classes) {
                if ($from === $name || $to === $name) {
                    $local[$from][$to] = $classes;
                }
            }
        }

        $lines = [
            '# Module '.$name,
            '',
            '> Generated by `php artisan cordon:docs` from the code. Do not edit by hand.',
            '',
            '| | |',
            '|---|---|',
            '| Namespace | `'.$module->namespace.'` |',
            '| Path | `'.Paths::relative($basePath, $module->path).'` |',
            '| Declared dependencies (`depends_on`) | '.match (true) {
                $module->dependsOn === null => '(not declared)',
                $module->dependsOn === [] => '(none)',
                default => implode(', ', $module->dependsOn),
            }.' |',
            '| Open (every class public) | '.($module->open ? 'yes' : 'no').' |',
            '',
            '## Dependencies',
            '',
            ...$this->diagram($neighbours, $local, $internal, $name),
            '',
            '## Public API',
            '',
            ...$this->bullets($this->publicApi($module, $snapshot), 'No public classes yet.'),
            '',
            '## Uses',
            '',
            ...$this->classTable($outgoing, $snapshot, 'Does not use other modules.'),
            '',
            '## Used by',
            '',
            ...$this->classTable($incoming, $snapshot, 'Not used by other modules.', $module),
            '',
            '## Events',
            '',
            ...$this->moduleEvents($name, $events),
            '',
            '## Violations',
            '',
        ];

        $own = array_values(array_filter($violations, static fn (Violation $v): bool => ModuleFilter::involves($v, $name)));

        if ($own === []) {
            $lines[] = 'None.';
        }

        foreach ($own as $violation) {
            $location = $violation->file === null
                ? ''
                : ' `'.Paths::relative($basePath, $violation->file).($violation->line === null ? '' : ':'.$violation->line).'`';

            $lines[] = sprintf('- **%s**%s: %s', $violation->rule, $location, $violation->message);
        }

        return implode("\n", $lines)."\n";
    }

    private function eventInventory(EventInventory $events, ?string $basePath): string
    {
        $lines = [
            '# Events',
            '',
            '> Generated by `php artisan cordon:docs` from the code. Do not edit by hand.',
            '',
            'Events are classes under a module\'s `Events` namespace, or dispatched with `event(new X)`, `Event::dispatch()` or registered with `Event::listen()`.',
            '',
        ];

        if ($events->events === []) {
            $lines[] = 'No events found.';

            return implode("\n", $lines)."\n";
        }

        $lines[] = '| Event | Module | Published by | Listened by |';
        $lines[] = '|---|---|---|---|';

        foreach ($events->events as $event) {
            $lines[] = sprintf(
                '| `%s` | %s | %s | %s |',
                $event->fqcn,
                $event->module,
                $this->usages($event->publishers, $basePath),
                $this->usages($event->listeners, $basePath),
            );
        }

        return implode("\n", $lines)."\n";
    }

    /**
     * @param  list<string>  $nodes
     * @param  array<string, array<string, array<string, true>>>  $dependencies
     * @param  array<string, true>  $internal
     * @return list<string>
     */
    private function diagram(array $nodes, array $dependencies, array $internal, ?string $highlight = null): array
    {
        $ids = array_flip($nodes);
        $lines = ['```mermaid', 'flowchart LR'];

        foreach ($nodes as $index => $node) {
            $lines[] = sprintf('    m%d["%s"]', $index, str_replace('"', '#quot;', $node));
        }

        $red = [];
        $link = 0;

        foreach ($dependencies as $from => $targets) {
            foreach ($targets as $to => $classes) {
                if (! isset($ids[$from], $ids[$to])) {
                    continue;
                }

                $lines[] = sprintf('    m%d -->|%d| m%d', $ids[$from], count($classes), $ids[$to]);

                if (isset($internal[$from.'|'.$to])) {
                    $red[] = $link;
                }

                $link++;
            }
        }

        if ($red !== []) {
            $lines[] = '    linkStyle '.implode(',', $red).' stroke:#d33,stroke-width:2px';
        }

        if ($highlight !== null && isset($ids[$highlight])) {
            $lines[] = sprintf('    style m%d stroke-width:3px', $ids[$highlight]);
        }

        $lines[] = '```';

        return $lines;
    }

    /**
     * @param  array<string, array<string, true>>  $byModule  module => class => true
     * @return list<string>
     */
    private function classTable(array $byModule, Snapshot $snapshot, string $empty, ?Module $owner = null): array
    {
        if ($byModule === []) {
            return [$empty];
        }

        $lines = ['| Module | Classes |', '|---|---|'];

        foreach ($byModule as $module => $classes) {
            $target = $owner ?? $snapshot->context->modules->get($module);
            $names = [];

            foreach (array_keys($classes) as $class) {
                $public = $target === null
                    || $snapshot->context->policy->isPublic($class, $target, $snapshot->context->symbols->get($class));

                $names[] = '`'.($target === null ? $class : $target->relativeName($class)).'`'.($public ? '' : ' (internal)');
            }

            $lines[] = sprintf('| %s | %s |', $module, implode(', ', $names));
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function moduleEvents(string $module, EventInventory $events): array
    {
        $sections = [
            'Owned' => $events->ownedBy($module),
            'Published' => $events->publishedBy($module),
            'Listened to' => $events->listenedBy($module),
        ];

        $lines = [];

        foreach ($sections as $title => $entries) {
            $lines[] = sprintf('- %s: %s', $title, $entries === []
                ? 'none'
                : implode(', ', array_map(static fn (EventEntry $entry): string => '`'.$entry->fqcn.'`', $entries)));
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function publicApi(Module $module, Snapshot $snapshot): array
    {
        $classes = [];

        foreach ($snapshot->analyses as $analysis) {
            foreach ($analysis->declarations as $declaration) {
                if ($module->ownsClass($declaration->fqcn)
                    && $snapshot->context->modules->forClass($declaration->fqcn)?->name === $module->name
                    && $snapshot->context->policy->isPublic($declaration->fqcn, $module, $declaration)) {
                    $classes[] = '`'.$module->relativeName($declaration->fqcn).'`';
                }
            }
        }

        sort($classes);

        return array_values(array_unique($classes));
    }

    /**
     * @param  list<Edge>  $edges
     * @return array<string, array<string, array<string, true>>>
     */
    private function dependencies(array $edges): array
    {
        $dependencies = [];

        foreach ($edges as $edge) {
            $dependencies[$edge->from->name][$edge->to->name][$edge->reference->target] = true;
        }

        ksort($dependencies);

        foreach ($dependencies as &$targets) {
            ksort($targets);

            foreach ($targets as &$classes) {
                ksort($classes);
            }
        }

        return $dependencies;
    }

    /**
     * @param  list<Violation>  $violations
     * @return array<string, true>
     */
    private function internalPairs(array $violations): array
    {
        $pairs = [];

        foreach ($violations as $violation) {
            if ($violation->rule === InternalAccessRule::ID && $violation->sourceModule !== null && $violation->targetModule !== null) {
                $pairs[$violation->sourceModule.'|'.$violation->targetModule] = true;
            }
        }

        return $pairs;
    }

    /**
     * @param  array<string, array<string, array<string, true>>>  $dependencies
     * @return list<string>
     */
    private function usedBy(string $module, array $dependencies): array
    {
        $users = [];

        foreach ($dependencies as $from => $targets) {
            if (isset($targets[$module])) {
                $users[] = $from;
            }
        }

        return $users;
    }

    /**
     * @param  list<array{module: string, class: string|null, file: string, line: int}>  $usages
     */
    private function usages(array $usages, ?string $basePath): string
    {
        if ($usages === []) {
            return '-';
        }

        return implode('<br>', array_map(
            static fn (array $usage): string => sprintf(
                '%s `%s`',
                $usage['module'],
                $usage['class'] ?? Paths::relative($basePath, $usage['file']).':'.$usage['line'],
            ),
            $usages,
        ));
    }

    /**
     * @param  list<string>  $items
     */
    private function list(array $items): string
    {
        return $items === [] ? '-' : implode(', ', $items);
    }

    /**
     * @param  list<string>  $items
     * @return list<string>
     */
    private function bullets(array $items, string $empty): array
    {
        return $items === [] ? [$empty] : array_map(static fn (string $item): string => '- '.$item, $items);
    }

    private function fileName(Module $module): string
    {
        return 'modules/'.$module->name.'.md';
    }
}
